-- 1. Vi filtrerer benhårdt på 'Played' og tager KUN den absolut sidste opdatering
WITH CleanXG AS (
    SELECT 
        CONTESTANT_OPTAUUID,
        MATCH_ID,
        STAT_VALUE
    FROM KLUB_HVIDOVREIF.AXIS.OPTA_MATCHEXPECTEDGOALS
    WHERE TOURNAMENTCALENDAR_OPTAUUID = 'dyjr458hcmrcy87fsabfsy87o'
      AND MATCH_STATUS = 'Played' -- Vi vil kun have de færdige kampe
    QUALIFY ROW_NUMBER() OVER (PARTITION BY MATCH_ID, PLAYER_OPTAUUID, STAT_TYPE ORDER BY MATCH_DATE DESC) = 1
),
CleanStats AS (
    SELECT 
        MATCH_OPTAUUID,
        CONTESTANT_OPTAUUID,
        STAT_TYPE,
        STAT_TOTAL
    FROM KLUB_HVIDOVREIF.AXIS.OPTA_MATCHSTATS
    WHERE TOURNAMENTCALENDAR_OPTAUUID = 'dyjr458hcmrcy87fsabfsy87o'
    -- Her antager vi, at dubletterne i matchstats også kan fjernes ved at tage den nyeste
    QUALIFY ROW_NUMBER() OVER (PARTITION BY MATCH_OPTAUUID, CONTESTANT_OPTAUUID, STAT_TYPE ORDER BY STAT_TOTAL DESC) = 1
)
-- 2. Nu summerer vi de rensede tal
SELECT 
    s.CONTESTANT_OPTAUUID,
    COUNT(DISTINCT s.MATCH_OPTAUUID) as ACTUAL_MATCHES,
    SUM(CASE WHEN s.STAT_TYPE = 'goals' THEN s.STAT_TOTAL ELSE 0 END) as TOTAL_GOALS,
    ROUND(SUM(x.STAT_VALUE), 2) as TOTAL_XG,
    ROUND(TOTAL_GOALS - TOTAL_XG, 2) as XG_DIFF
FROM CleanStats s
LEFT JOIN CleanXG x ON s.CONTESTANT_OPTAUUID = x.CONTESTANT_OPTAUUID 
                   AND s.MATCH_OPTAUUID = x.MATCH_ID
GROUP BY 1
ORDER BY TOTAL_GOALS DESC;
